server:
  error:
    include-stacktrace: on_param

spring:
  application:
    name: springboot-essentials
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/anime?&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

info:
  app: Spring Boot 2 Essentials By Luan Kenzley
  website: https://devdojo.academy
  github: http://github.com/luankenzley/springboot-essentials